
- name: update to latest stable
  sudo: yes
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: install security packages
  sudo: yes
  apt: pkg={{item}} state=latest
  with_items:
    - unattended-upgrades
    - fail2ban
    - update-notifier-common

- name: auto-update
  sudo: yes
  template: src=auto-upgrades.j2 dest=/etc/apt/apt.conf.d/20auto-upgrades

- name: check if a reboot is required
  register: file
  stat: path=/var/run/reboot-required get_md5=no
